version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Puerto AMQP
      - "15672:15672"  # Interfaz de administración
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
    networks:
      - my-network

  wakanda-server:
    build:
      context: .
    container_name: wakanda-server
    ports:
      - "8761:8761"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: myuser
      SPRING_RABBITMQ_PASSWORD: mypassword
    depends_on:
      - rabbitmq
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
