spring:
  application:
    name: health-service

  eureka:
    client:
      service-url:
        defaultZone: http://eureka-server:8761/eureka/
      register-with-eureka: true
      fetch-registry: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: myuser
    password: mypassword

server:
  port: 8082  # Puerto específico para el servicio de Health

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework: INFO
    com.example.wakanda: DEBUG
