spring:
  application:
    name: eureka-server
  profiles:
    active: health-service

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: myuser
    password: mypassword

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    server:
      enable-self-preservation: false

  security:
    user:
      name: admin
      password: admin
    basic:
      enabled: false
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    security:
      enabled: false
    endpoint:
      health:
        show-details: always


traffic:
  queue:
    name: trafficQueue
  exchange:
    name: trafficExchange
  routing:
    key: trafficKey

server:
  port: 8761
